#!/usr/bin/env zsh

() {
	local file
	for file in $(git diff --name-only --staged); do
		[[ -f $file ]] || continue

		local file_ext="${file##*.}"
		if [[ "$file_ext" == "rs" ]]; then
			cargo +nightly fmt -- "$file" --check || exit 1
		fi
	done

	cargo clippy --workspace || exit 1
	cargo test --workspace --color='always'
}
